### ISSUE TITLE
mobx store里的数组数据不能用于computed?

### ISSUE THREAD

**Issue by chenzhutian** [wechat-miniprogram/mobx-miniprogram-bindings#13]
复现例子:
https://developers.weixin.qq.com/s/hgT6RCmL7Fkm

`accounts`是store里的一个数组
```
export const store = observable({

  // 数据字段
  numA: 4,
  numB: 5,
  accounts: [4, 5, 6],

  add: action(function() {
    this.accounts = [1, 2, 3]
  }),

  // actions
  update: action(function () {
    this.numA = this.numA + 1
    this.numB = this.numA + 1
  })

})
```

当启动的时候, 会报一个bug说
```
VM824:1 MiniProgramError
data.accounts.reduce is not a function
TypeError: data.accounts.reduce is not a function
    at sum (http://127.0.0.1:63254/appservice/index/components/computed-example.js:17:28)
    at http://127.0.0.1:63254/appservice/components/index.js:392:21
    at Array.forEach (<anonymous>)
    at Ge.created (http://127.0.0.1:63254/appservice/components/index.js:385:34)
    at r.safeCallback (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1775504)
    at r.call (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1775397)
    at Function.M._advancedCreate (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1823182)
    at r.createComponent (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1834383)
    at e (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1919566)
    at e (http://127.0.0.1:63254/appservice/__dev__/WAService.js:2:1920093)
```

```
Component({
  behaviors: [behaviorTest, storeBindingsBehavior, computedBehavior],
  computed: {
    sum(data) {
      console.log(data.accounts)
      return data.accounts.reduce((s, o) => s + o, 0)
    },
  },
  data: {
    a: 1,
    b: 1,
  },
  storeBindings: {
    store,
    fields: ['numA', 'numB','accounts'],
    actions: {
      buttonTap: 'add'
    },
  },

  methods: {
    onTap() {
      console.log(this.data.accounts[0], this.data.accounts.reduce((s, o) => s + o, 0))
      this.buttonTap()
    }
  }
})
```

**Comment by LastLeaf** [comment]
仔细排查之后发现三个问题：

* computed 先于 mobx 填入 data （ computed 在 created 时，而 mobx 在 attached 时），导致第一次执行 computed 函数的时候 mobx 管理的字段值还不存在；
* mobx setData 时漏了 toJS 调用导致其在 computed 函数里面缺了 Array 原型方法；
* computed 3.0.0 中对 undefined 值处理得不够好导致有时返回了一个空对象而非 undefined 本身。、

**Comment by chenzhutian** [comment]
对, 我在 https://github.com/wechat-miniprogram/computed/issues/43 里面其实已经fix了这几个问题

**Comment by chenzhutian** [comment]
我自己写了一个纯ts版的mobx-miniprogram-binding和computed, fix了一些bug, 也解决了一些type defined的问题
如果有你们公司允许的话我可以提个pr

**Comment by LastLeaf** [comment]
PR 当然是欢迎的！

**Comment by LastLeaf** [comment]
第三点是有特殊用意的。我们正在讨论原因和解决方式。

**Comment by chenzhutian** [comment]
好的, 我的确没太懂那个的用意

**Comment by LastLeaf** [comment]
Fixed in v2.0.0
