### ISSUE TITLE
一个页面中可以绑定两个store么？

### ISSUE THREAD

**Issue by jerryjiao** [wechat-miniprogram/mobx-miniprogram-bindings#3]
怎样一个页面绑定两个store呢？
现在好像绑定的参数名不叫store就会报错,所以一个页面只能绑定一个store么？

eg:
import { createStoreBindings } from 'mobx-miniprogram-bindings'
import {store as plpstore} from '../../models/plpStore'

 onLoad: function () {
    this.storeBindings = createStoreBindings(this, {
      plpstore,
      actions: ['getItemList', 'pageTurn']
    })
    this.getItemList()
    console.log('list--->')
  },

然后就会报错：
![企业微信截图_20191021182203](https://user-images.githubusercontent.com/12718716/67197607-bf33e400-f42f-11e9-9064-2e592944f47d.png)

如果去掉 as plpstore,就不会报错了

**Comment by jerryjiao** [comment]
用两次createStoreBindings就行了，关闭了

**Comment by callmesoul** [comment]
@jerryjiao  发现不行啊
```
import { store } from '../../store'
import { store as shopStore } from '../../store/shop-detail'

 this.storeBindings = createStoreBindings(this, {
        store,
        fields: ['userInfo'],
    })
    this.storeBindings = createStoreBindings(this, {
      shopStore,
      fields: ['pets','shop'],
      actions: ['setPets'],
 })
```
报错
```
VM24173:1 thirdScriptError
[mobx-miniprogram] no store specified;at "pages/shop/detail" page lifeCycleMethod onLoad function
Error: [mobx-miniprogram] no store specified
    at _createActions (http://127.0.0.1:43542/appservice/miniprogram_npm/mobx-miniprogram-bindings/index.js:287:13)
    at createStoreBindings (http://127.0.0.1:43542/appservice/miniprogram_npm/mobx-miniprogram-bindings/index.js:400:5)
    at ye.onLoad (http://127.0.0.1:43542/appservice/pages/shop/detail.js:44:75)
    at ye.<anonymous> (WAService.js:1:1353019)
    at ye.p.__callPageLifeTime__ (WAService.js:1:1352764)
    at Tt (WAService.js:1:1367714)
    at WAService.js:1:1370885
    at xt (WAService.js:1:1371378)
    at Function.<anonymous> (WAService.js:1:1374768)
    at i.<anonymous> (WAService.js:1:1344283)
```

发现名字一定要store才行，换其他名字都会报错这个错，哪怕只有一个store
但是是固定用store的话，两个store就会冲突，换别名也报错

**Comment by LastLeaf** [comment]
改个名

```js
this.storeBindings2 = createStoreBindings(this, {
      store: shopStore,
      fields: ['pets','shop'],
      actions: ['setPets'],
})
```

**Comment by callmesoul** [comment]
可以了，写法问题...
```
store: shopStroe
```
为什么名字为`store`时，就可以直接
```
store 
```
呢？
